[build-system]
requires = ["setuptools>=61.0","setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "groundStation"
version = "0.1.0"
dependencies = ["pyqt5>=5.15.10"]
authors = [
    {name="Nathan Samuell", email="nathansamuell@duck.com"},
]
readme = "README.md"
licence = {file = "LICENSE"}
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Development Status :: 2 - Pre-Alpha",
]