name: Release FlightControl

on:
  push:
    # Trigger only when a tag is pushed to the main branch
    tags:
      - 'v*'  # Matches any tag like v1.0.0, v1.2.3, etc.
    branches:
      - 'main'  # Only allow publishing for tags on the main branch

jobs:
    pypi-publish:
        if: startsWith(github.ref, 'refs/tags/')
        name: upload release to PyPI
        runs-on: ubuntu-latest
            # Specifying a GitHub environment is optional, but strongly encouraged
        environment: release
        permissions:
            # IMPORTANT: this permission is mandatory for trusted publishing
            id-token: write
        steps:
            # retrieve your distributions here
      
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
